# Generated by Django 4.2.5 on 2023-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('warehouse', models.CharField(max_length=50)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
