# Generated by Django 4.2.5 on 2023-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_authenticated',
            field=models.BooleanField(null=True),
        ),
    ]
