# Generated by Django 4.2.5 on 2023-10-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_authenticated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
