# Generated by Django 4.2.5 on 2023-11-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='orders',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
